#spring:
#  application:
#    name: USER-SERVICE
#  config:
#    import: "optional:configserver:http://localhost:8088"
#
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/Gammastack
#    username: root
#    password: root
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    hibernate.dialect: org.hibernate.dialect.MySQLDialect
